"""change in models

Revision ID: 1c5fb69d1eab
Revises: e0c3e87bd5d8
Create Date: 2022-09-19 19:24:33.462496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5fb69d1eab'
down_revision = 'e0c3e87bd5d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contacts_to_emails')
    op.drop_table('contacts_to_phones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_to_phones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='contacts_to_phones_contact_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contacts_to_phones_pkey')
    )
    op.create_table('contacts_to_emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='contacts_to_emails_contact_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contacts_to_emails_pkey')
    )
    op.drop_table('phones')
    op.drop_table('emails')
    # ### end Alembic commands ###
