"""change names of columns

Revision ID: 22b393ea0d6f
Revises: 5e0f9d8c6a87
Create Date: 2022-09-19 18:53:28.535920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b393ea0d6f'
down_revision = '5e0f9d8c6a87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones', sa.Column('phone', sa.String(length=20), nullable=False))
    op.drop_column('phones', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phones', sa.Column('value', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('phones', 'phone')
    # ### end Alembic commands ###
