"""add table Phone

Revision ID: 55ff499af147
Revises: 5247ceb6adcf
Create Date: 2022-09-19 15:53:31.491805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ff499af147'
down_revision = '5247ceb6adcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('contacts', 'cell_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('cell_phone', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_table('phones')
    # ### end Alembic commands ###
