"""add columnt to ContactGroup

Revision ID: 5e0f9d8c6a87
Revises: 9f34aa924675
Create Date: 2022-09-19 18:07:33.193054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0f9d8c6a87'
down_revision = '9f34aa924675'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_to_groups', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts_to_groups', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts_to_groups', type_='foreignkey')
    op.drop_column('contacts_to_groups', 'contact_id')
    # ### end Alembic commands ###
