"""change in models

Revision ID: 869040381aa5
Revises: 1c5fb69d1eab
Create Date: 2022-09-20 11:09:38.111402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869040381aa5'
down_revision = '1c5fb69d1eab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
